---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crossplane
type: Opaque
data:
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQTJXTzRVRVEzQ1IzNkc2NUsKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gK05hdTZIUkpyZEFmUVFrUzA1TG0rTFNNYjA2N3NoMVhJc1hlV0dlSgo=
